[workspace]
resolver = "3"
members = [ "communication","config_utility", "main_menu", "misc", "protocol"]

[workspace.package]
authors = ["Dmitry Akimov <akimov@machunit.com>"]

[workspace.dependencies]
configparser = "3.1.0"
thiserror = "2.0.12"
log = "0.4.27"
env_logger = "0.11.8"
