[workspace]
resolver = "3"
members = ["config_utility", "main_menu", "misc", "protocol"]

[workspace.package]
authors = ["Dmitry Akimov <akimov@machunit.com>"]

[workspace.dependencies]
thiserror = "2.0.12"
log = "0.4.27"
env_logger = "0.11.8"
