[build]
build-std = false                              # do not build the std library. has precedence over xargo                    
default-target = "arm-unknown-linux-gnueabihf" 


[build.zig]
enable = true                 # enable or disable the use of zig cc
version = "2.28"              # the glibc version to use
   
