[package]
name = "config_utility"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
configparser = {workspace = true}
protocol = { path = "../protocol" }
misc = { path = "../misc" }
log = { workspace = true }
env_logger = { workspace = true }
