[package]
name = "protocol"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
log = { workspace = true }
crc = "3.3.0"
thiserror = { workspace = true }
serialport = {version = "4.7.2", default-features = false}
