[package]
name = "main_menu"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
misc = { path = "../misc" }
inquire = { version = "0.7.5", features = ["date"] }
colored = "3.0.0"
terminal-menu = "3.0.0"
crossterm = "0.25.0"