[package]
name = "communication"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
misc = { path = "../misc" }
configparser = {workspace = true}
serialport = {workspace = true}